# -*- coding: utf-8 -*-
regions = {
    88: 'States Ex-Yugoslavia, unspecified',
    89: 'Europe, regional',
    189: 'North of Sahara, regional',
    289: 'South of Sahara, regional',
    298: 'Africa, regional',
    380: 'West Indies, regional',
    389: 'North and Central America, regional',
    489: 'South America, regional',
    498: 'America, regional',
    589: 'Middle East, regional',
    619: 'Central Asia, regional',
    679: 'South Asia, regional',
    689: 'South and Central Asia, regional',
    789: 'Far East Asia, regional',
    798: 'Asia, regional',
    889: 'Oceania, regional',
    998: 'Developing countries, unspecified'
}

countries = {'AF': 'AFGHANISTAN',
             'AX': 'ALAND ISLANDS',
             'AL': 'ALBANIA',
             'DZ': 'ALGERIA',
             'AS': 'AMERICAN SAMOA',
             'AD': 'ANDORRA',
             'AO': 'ANGOLA',
             'AI': 'ANGUILLA',
             'AQ': 'ANTARCTICA',
             'AG': 'ANTIGUA AND BARBUDA',
             'AR': 'ARGENTINA',
             'AM': 'ARMENIA',
             'AW': 'ARUBA',
             'AU': 'AUSTRALIA',
             'AT': 'AUSTRIA',
             'AZ': 'AZERBAIJAN',
             'BS': 'BAHAMAS (THE)',
             'BH': 'BAHRAIN',
             'BD': 'BANGLADESH',
             'BB': 'BARBADOS',
             'BY': 'BELARUS',
             'BE': 'BELGIUM',
             'BZ': 'BELIZE',
             'BJ': 'BENIN',
             'BM': 'BERMUDA',
             'BT': 'BHUTAN',
             'BO': 'BOLIVIA (PLURINATIONAL STATE OF)',
             'BQ': 'BONAIRE, SAINT EUSTATIUS AND SABA',
             'BA': 'BOSNIA AND HERZEGOVINA',
             'BW': 'BOTSWANA',
             'BV': 'BOUVET ISLAND',
             'BR': 'BRAZIL',
             'IO': 'BRITISH INDIAN OCEAN TERRITORY (THE)',
             'BN': 'BRUNEI DARUSSALAM',
             'BG': 'BULGARIA',
             'BF': 'BURKINA FASO',
             'BI': 'BURUNDI',
             'KH': 'CAMBODIA',
             'CM': 'CAMEROON',
             'CA': 'CANADA',
             'CV': 'CAPE VERDE',
             'KY': 'CAYMAN ISLANDS (THE)',
             'CF': 'CENTRAL AFRICAN REPUBLIC (THE)',
             'TD': 'CHAD',
             'CL': 'CHILE',
             'CN': 'CHINA',
             'CX': 'CHRISTMAS ISLAND',
             'CC': 'COCOS (KEELING) ISLANDS (THE)',
             'CO': 'COLOMBIA',
             'KM': 'COMOROS (THE)',
             'CG': 'CONGO (THE)',
             'CD': 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
             'CK': 'COOK ISLANDS (THE)',
             'CR': 'COSTA RICA',
             'CI': 'CÔTE D’IVOIRE',
             'HR': 'CROATIA',
             'CU': 'CUBA',
             'CW': 'CURAÇAO',
             'CY': 'CYPRUS',
             'CZ': 'CZECH REPUBLIC (THE)',
             'DK': 'DENMARK',
             'DJ': 'DJIBOUTI',
             'DM': 'DOMINICA',
             'DO': 'DOMINICAN REPUBLIC (THE)',
             'EC': 'ECUADOR',
             'EG': 'EGYPT',
             'SV': 'EL SALVADOR',
             'GQ': 'EQUATORIAL GUINEA',
             'ER': 'ERITREA',
             'EE': 'ESTONIA',
             'ET': 'ETHIOPIA',
             'FK': 'FALKLAND ISLANDS (THE) [MALVINAS]',
             'FO': 'FAROE ISLANDS (THE)',
             'FJ': 'FIJI',
             'FI': 'FINLAND',
             'FR': 'FRANCE',
             'GF': 'FRENCH GUIANA',
             'PF': 'FRENCH POLYNESIA',
             'TF': 'FRENCH SOUTHERN TERRITORIES',
             'GA': 'GABON',
             'GM': 'GAMBIA',
             'GE': 'GEORGIA',
             'DE': 'GERMANY',
             'GH': 'GHANA',
             'GI': 'GIBRALTAR',
             'GR': 'GREECE',
             'GL': 'GREENLAND',
             'GD': 'GRENADA',
             'GP': 'GUADELOUPE',
             'GU': 'GUAM',
             'GT': 'GUATEMALA',
             'GG': 'GUERNSEY',
             'GN': 'GUINEA',
             'GW': 'GUINEA-BISSAU',
             'GY': 'GUYANA',
             'HT': 'HAITI',
             'HM': 'HEARD ISLAND AND MCDONALD ISLANDS',
             'VA': 'HOLY SEE (THE)',
             'HN': 'HONDURAS',
             'HK': 'HONG KONG',
             'HU': 'HUNGARY',
             'IS': 'ICELAND',
             'IN': 'INDIA',
             'ID': 'INDONESIA',
             'IR': 'IRAN (ISLAMIC REPUBLIC OF)',
             'IQ': 'IRAQ',
             'IE': 'IRELAND',
             'IM': 'ISLE OF MAN',
             'IL': 'ISRAEL',
             'IT': 'ITALY',
             'JM': 'JAMAICA',
             'JP': 'JAPAN',
             'JE': 'JERSEY',
             'JO': 'JORDAN',
             'KZ': 'KAZAKHSTAN',
             'KE': 'KENYA',
             'KI': 'KIRIBATI',
             'KP': 'KOREA (DEMOCRATIC PEOPLE’S REPUBLIC OF)',
             'KR': 'KOREA (REPUBLIC OF)',
             'XK': 'KOSOVO',
             'KW': 'KUWAIT',
             'KG': 'KYRGYZSTAN',
             'LA': 'LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)',
             'LV': 'LATVIA',
             'LB': 'LEBANON',
             'LS': 'LESOTHO',
             'LR': 'LIBERIA',
             'LY': 'LIBYAN ARAB JAMAHIRIYA',
             'LI': 'LIECHTENSTEIN',
             'LT': 'LITHUANIA',
             'LU': 'LUXEMBOURG',
             'MO': 'MACAO',
             'MK': 'MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)',
             'MG': 'MADAGASCAR',
             'MW': 'MALAWI',
             'MY': 'MALAYSIA',
             'MV': 'MALDIVES',
             'ML': 'MALI',
             'MT': 'MALTA',
             'MH': 'MARSHALL ISLANDS (THE)',
             'MQ': 'MARTINIQUE',
             'MR': 'MAURITANIA',
             'MU': 'MAURITIUS',
             'YT': 'MAYOTTE',
             'MX': 'MEXICO',
             'FM': 'MICRONESIA (FEDERATED STATES OF)',
             'MD': 'MOLDOVA (REPUBLIC OF)',
             'MC': 'MONACO',
             'MN': 'MONGOLIA',
             'ME': 'MONTENEGRO',
             'MS': 'MONTSERRAT',
             'MA': 'MOROCCO',
             'MZ': 'MOZAMBIQUE',
             'MM': 'MYANMAR',
             'NA': 'NAMIBIA',
             'NR': 'NAURU',
             'NP': 'NEPAL',
             'NL': 'NETHERLANDS (THE)',
             'AN': 'NETHERLAND ANTILLES',
             'NC': 'NEW CALEDONIA',
             'NZ': 'NEW ZEALAND',
             'NI': 'NICARAGUA',
             'NE': 'NIGER (THE)',
             'NG': 'NIGERIA',
             'NU': 'NIUE',
             'NF': 'NORFOLK ISLAND',
             'MP': 'NORTHERN MARIANA ISLANDS (THE)',
             'NO': 'NORWAY',
             'OM': 'OMAN',
             'PK': 'PAKISTAN',
             'PW': 'PALAU',
             'PS': 'PALESTINIAN TERRITORY, OCCUPIED',
             'PA': 'PANAMA',
             'PG': 'PAPUA NEW GUINEA',
             'PY': 'PARAGUAY',
             'PE': 'PERU',
             'PH': 'PHILIPPINES (THE)',
             'PN': 'PITCAIRN',
             'PL': 'POLAND',
             'PT': 'PORTUGAL',
             'PR': 'PUERTO RICO',
             'QA': 'QATAR',
             'RE': 'REUNION',
             'RO': 'ROMANIA',
             'RU': 'RUSSIAN FEDERATION (THE)',
             'RW': 'RWANDA',
             'BL': 'SAINT BARTHÉLEMY',
             'SH': 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
             'KN': 'SAINT KITTS AND NEVIS',
             'LC': 'SAINT LUCIA',
             'MF': 'SAINT MARTIN (FRENCH PART)',
             'PM': 'SAINT PIERRE AND MIQUELON',
             'VC': 'SAINT VINCENT AND THE GRENADINES',
             'WS': 'SAMOA',
             'SM': 'SAN MARINO',
             'ST': 'SAO TOME AND PRINCIPE',
             'SA': 'SAUDI ARABIA',
             'SN': 'SENEGAL',
             'RS': 'SERBIA',
             'SC': 'SEYCHELLES',
             'SL': 'SIERRA LEONE',
             'SG': 'SINGAPORE',
             'SX': 'SINT MAARTEN (DUTCH PART)',
             'SK': 'SLOVAKIA',
             'SI': 'SLOVENIA',
             'SB': 'SOLOMON ISLANDS',
             'SO': 'SOMALIA',
             'ZA': 'SOUTH AFRICA',
             'GS': 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
             'SS': 'SOUTH SUDAN',
             'ES': 'SPAIN',
             'LK': 'SRI LANKA',
             'SD': 'SUDAN (THE)',
             'SR': 'SURINAME',
             'SJ': 'SVALBARD AND JAN MAYEN',
             'SZ': 'SWAZILAND',
             'SE': 'SWEDEN',
             'CH': 'SWITZERLAND',
             'SY': 'SYRIAN ARAB REPUBLIC',
             'TW': 'TAIWAN (PROVINCE OF CHINA)',
             'TJ': 'TAJIKISTAN',
             'TZ': 'TANZANIA, UNITED REPUBLIC OF',
             'TH': 'THAILAND',
             'TL': 'TIMOR-LESTE',
             'TG': 'TOGO',
             'TK': 'TOKELAU',
             'TO': 'TONGA',
             'TT': 'TRINIDAD AND TOBAGO',
             'TN': 'TUNISIA',
             'TR': 'TURKEY',
             'TM': 'TURKMENISTAN',
             'TC': 'TURKS AND CAICOS ISLANDS (THE)',
             'TV': 'TUVALU',
             'UG': 'UGANDA',
             'UA': 'UKRAINE',
             'AE': 'UNITED ARAB EMIRATES (THE)',
             'GB': 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
             'US': 'UNITED STATES OF AMERICA (THE)',
             'UM': 'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
             'UY': 'URUGUAY',
             'UZ': 'UZBEKISTAN',
             'VU': 'VANUATU',
             'VE': 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
             'VN': 'VIET NAM',
             'VG': 'VIRGIN ISLANDS (BRITISH)',
             'VI': 'VIRGIN ISLANDS (U.S.)',
             'WF': 'WALLIS AND FUTUNA',
             'EH': 'WESTERN SAHARA',
             'YE': 'YEMEN',
             'ZM': 'ZAMBIA',
             'ZW': 'ZIMBABWE'}

organisations = {
    'GB-GOV': 'DIFD',
    '46002': 'AFDB'
}
